update item_set_stats set content = '生命值' where content ='HP';
update item_set_stats set content = '伤害' where content ='Damage';
update item_set_stats set content = '锁定' where content ='Lock';
update item_set_stats set content = '先手' where content ='Initiative';
update item_set_stats set content = '闪避' where content ='Dodge';
update item_set_stats set content = '智慧之火' where content ='Intelligence';
update item_set_stats set content = '抗性' where content ='Resist';
update item_set_stats set content = '背刺伤害' where content ='Backstab';
update item_set_stats set content = '暴击' where content ='Critical';
update item_set_stats set content = '格挡' where content ='Block';
update item_set_stats set content = '行动力' where content ='AP';
update item_set_stats set content = '移动力' where content ='MP';
update item_set_stats set content = '创生力' where content ='WP';
update item_set_stats set content = '统帅' where content ='Control';
update item_set_stats set content = '洞察' where content ='Perception' ;
update item_set_stats set content = '意志' where content ='Willpower' ;
update item_set_stats set content = '勘探' where content ='Prospecting' ;
update item_set_stats set content = '治疗' where content ='Heals' ;
update item_set_stats set content = '悟性' where content ='Wisdom' ;
update item_set_stats set content = '幸运之水' where content ='chance' ;
update item_set_stats set content = '抗性' where content = 'Resist.' ;
update item_set_stats set content = '召唤物伤害' where content ='CMC' ;
update item_set_stats set content = '坚韧之地' where content ='Strength' ;
update item_set_stats set content = '射程' where content ='Range' ;
update item_set_stats set content = '技能等级' where content ='Lvl.' ;
update item_set_stats set content = '敏捷之风' where content ='Agility' ;
