update items set item_type_id =306 ,item_type ="伐木工采集物" where item_type = "Lumberjack's Harvests";
update items set item_type_id =308 ,item_type ="渔夫的采集物" where item_type = "Fisherman's Harvests";
update items set item_type_id =309 ,item_type ="农夫的采集物" where item_type = "Farmer's Harvests";
update items set item_type_id =313 ,item_type ="草药学采集物" where item_type = "Herbalist's Harvests";
update items set item_type_id =317 ,item_type ="钥匙"	   where item_type = "Keys";
update items set item_type_id =327 ,item_type ="伐木工制造物" where item_type = "Lumberjack's Refinements";
update items set item_type_id =370 ,item_type ="戒指"	   where item_type = "Ring";
update items set item_type_id =393 ,item_type ="农夫的制造物" where item_type = "Farmer's Refinements";
update items set item_type_id =415 ,item_type ="庇护袋家具"  where item_type = "Haven Bag Furniture";
update items set item_type_id =416 ,item_type ="庇护袋装饰品" where item_type = "Haven Bag Decorations";
update items set item_type_id =419 ,item_type ="种子"	   where item_type = "Seeds";
update items set item_type_id =421 ,item_type ="宠物表情宝石" where item_type = "Face Gem";
update items set item_type_id =422 ,item_type ="宠物外形宝石"where item_type = "Skin Gem";
update items set item_type_id =425 ,item_type ="武器资料"  where item_type = "Weapons: Archive";
update items set item_type_id =447 ,item_type ="制造机"   where item_type = "Crafting Machines";
update items set item_type_id =449 ,item_type ="海报"    where item_type = "Trade Room Decoration";
update items set item_type_id =463 ,item_type ="草药学制造物"where item_type = "Herbalist's Refinements";
update items set item_type_id =471 ,item_type ="鱼饵"    where item_type = "Hooks";
update items set item_type_id =472 ,item_type ="杂项道具"  where item_type = "Miscellaneous Items";
update items set item_type_id =476 ,item_type ="表情"    where item_type = "Emotes";
update items set item_type_id =496 ,item_type ="故事书"   where item_type = "Background Book";
update items set item_type_id =508 ,item_type ="服饰"	   where item_type = "Clothes";
update items set item_type_id =512 ,item_type ="称号"	   where item_type = "Titles";
update items set item_type_id =514 ,item_type ="矿工的制造物"where item_type = "Miner's Refinements";
update items set item_type_id =515 ,item_type ="花园装饰品" where item_type = "Garden Room Decoration";
update items set item_type_id =524 ,item_type ="活动"	   where item_type = "Event";
update items set item_type_id =529 ,item_type ="杂项道具"  where item_type = "Miscellaneous Resources";
update items set item_type_id =530 ,item_type ="动物掉落"  where item_type = "Animal Drop";
update items set item_type_id =531 ,item_type ="杂项掉落"  where item_type = "Miscellaneous Drop";
update items set item_type_id =532 ,item_type ="矿石掉落"  where item_type = "Ore Drop";
update items set item_type_id =533 ,item_type ="植物掉落"  where item_type = "Plant Drop";
update items set item_type_id =551 ,item_type ="任务道具"  where item_type = "Quest Items";
update items set item_type_id =567 ,item_type ="钓鱼制造品" where item_type = "Fisherman's Refinements";
update items set item_type_id =568 ,item_type ="畜牧业制造物" where item_type = "Trapper's Refinements";
update items set item_type_id =569 ,item_type ="厨师制作部件" where item_type = "Chef Components";
update items set item_type_id =570 ,item_type ="裁缝制作部件"	where item_type = " Tailor Components";
update items set item_type_id =571 ,item_type ="近战武器制作部件" where item_type = "CC Weapons Master Compone";
update items set item_type_id =572 ,item_type ="远程武器制作部件" where item_type = "Distance Weapons Master C";
update items set item_type_id =573 ,item_type ="魔法武器制作部件" where item_type = "Area Weapons Master Compo";
update items set item_type_id =574 ,item_type ="皮匠制作部件"	where item_type = "Leather Dealer Components";
update items set item_type_id =575 ,item_type ="铠甲制作部件"	where item_type = "Armorer Components";
update items set item_type_id =576 ,item_type ="珠宝制作部件"	where item_type = "Jeweler Components";
update items set item_type_id =577 ,item_type ="烘焙制作部件"	where item_type = "Baker Components";
update items set item_type_id =578 ,item_type ="工匠制作部件"	where item_type = "Handyman Components";
update items set item_type_id =581 ,item_type ="宠物装备"	where item_type = "Pet equipment";
update items set item_type_id =582 ,item_type ="宠物"		where item_type = "Pet";
update items set item_type_id =594 ,item_type ="宠物食物"	where item_type = "Food";
update items set item_type_id =595 ,item_type ="宠物染料"	where item_type = "Coloring";
update items set item_type_id =597 ,item_type ="奖励"	where item_type = "Rewards";
update items set item_type_id =601 ,item_type ="庇护宝石碎片"	where item_type = "Haven-Gem Pieces";
update items set item_type_id =603 ,item_type ="奖章"	where item_type = "Tokens";
update items set item_type_id =604 ,item_type ="套装"	where item_type = "Sets";
update items set item_type_id =606 ,item_type ="饰品盒"	where item_type = "Trinket Boxes";
update items set item_type_id =611 ,item_type ="坐骑"	where item_type = "Mounts";
update items set item_type_id =612 ,item_type ="酷洛大师"	where item_type = "Krosmaster";
update items set item_type_id =647 ,item_type ="时装"	where item_type = "Costume";
update items set item_type_id =646 ,item_type ="徽章"	where item_type = "Insignia";
update items set item_type_id =652 ,item_type ="建筑物装饰"	where item_type = "Building Decoration";
update items set item_type_id =682 ,item_type ="符文粉末"	where item_type = "Powder";
update items set item_type_id =683 ,item_type ="符文"	where item_type = "Rune";